covid_case/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("products.urls")),
    path("bag/", include("shopping_bag.urls")),
    path("", include("profiles.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name="products"),
    path('create/', views.create_product, name="create_product"),
    path('update/<int:id>/', views.update_product, name="update_product"),
    path('delete/<int:id>/', views.delete_product, name="delete_product"),
]

products/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

class Supplier(models.Model):
    supplier_name = models.CharField(max_length=settings.CONST_PROFILE_ATTR)
    description = models.CharField(max_length=settings.CONST_PROFILE_ATTR)
    def __str__(self):
        return self.supplier_name

class Product(models.Model):
    product_name = models.CharField(max_length=settings.CONST_PROFILE_ATTR)
    color = models.CharField(max_length=settings.CONST_PROFILE_ATTR)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = ResizedImageField(size=[400, 500], crop=['middle', 'center'],quality=100, upload_to='', default='noimage.jpeg')
    image_2 = ResizedImageField(size=[400, 500], crop=['middle', 'center'],quality=100, upload_to='', default='noimage.jpeg', null=True)
    number_in_stock = models.IntegerField(null=True , editable=True, default=0)
    is_active = models.BooleanField(default=True, null=True)
    created_by = models.CharField(max_length=settings.CONST_PROFILE_ATTR, null=True)
    created_date = models.TimeField(auto_now_add=True, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    is_deleted = models.BooleanField(default=False, null=True)
    def __str__(self):
        return self.color
    

products/forms.py
from django import forms
from .models import Product, Supplier
from crispy_forms.helper import FormHelper

class ProductForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.FileInput)
    image_2 = forms.ImageField(required=False, widget=forms.FileInput)
    supplier = forms.ModelChoiceField(queryset=Supplier.objects.all(), label='Supplier', widget=forms.Select)
    class Meta:
        model = Product
        fields = ["product_name", "color",
        "price","image", "image_2", "number_in_stock", "supplier"]
    
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for fieldname in ["product_name", "color",
        "price","image", "image_2", "number_in_stock", "supplier"]:
            self.fields[fieldname].helper = FormHelper()

products/views.py
from django.shortcuts import render, redirect, reverse
from .models import Product
from django.conf import settings
import requests
import json
from .forms import ProductForm
from django.contrib import messages

# Enabled this to get the screenshot for the readme using http://ami.responsivedesign.is/
# from django.views.decorators.clickjacking import xframe_options_exempt
# @xframe_options_exempt

def all_products(request):
    """
        A view that calls the api and if the status code is 200 
        pass the information from the api call to the template.
    """
    response = requests.get(
        settings.BASE_URL + settings.COUNTRY_DATA_WORLDMETERS)

    country_data = []
    if response.status_code == 200:
        all_data = json.loads(response.content.decode("utf-8"))
        try:
            for country in all_data:               
                    country_name = country["country"]
                    country_code = country["countryInfo"]["iso2"]
                    country_cases = country["cases"]
                    country_todayCases = country["todayCases"]
                    country_deaths = country["deaths"]
                    country_recovered = country["recovered"]
                    casesPerOneMillion = country["casesPerOneMillion"]
                    deathsPerOneMillion = country["deathsPerOneMillion"]
                    country_population = country["population"]
                    country_data_set = {
                        "country": country_name,
                        "code": country_code,
                        "cases": country_cases,
                        "todayCases": country_todayCases,
                        "deaths": country_deaths,
                        "recovered": country_recovered,
                        "population": country_population,
                        "casesPerOneMillion": casesPerOneMillion,
                        "deathsPerOneMillion": deathsPerOneMillion,
                    }
                    country_data.append(country_data_set)
        except Exception as e:
            # If there is any problem proccessing the response data - inform the user.
            print("Exception:", e)
            messages.error(request, "Sorry failed loading map data")
    else:
        # Problem with Disease.sh - inform user.
        messages.error(request, "There has been a problem getting map data. Please try again later.")
        
    products = Product.objects.filter(is_deleted=False).order_by("-number_in_stock")
    context = {
        "products": products,
        "country_data": country_data
    }
    return render(request, "products/all_products.html", context)


def create_product(request):
    """A view the creates a product"""
    form = ProductForm(request.POST or None, request.FILES)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("products"))

    context = {
        "form": form,
    }

    return render(request, "products/products_form.html", context)



def update_product(request, id):
    """This view gets a product from the database by using the id then updateing it if the form is valid"""
    product = Product.objects.get(id=id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse("products"))
    else:
        form = ProductForm(request.POST or None, instance=product)
    
    context = {
        "form": form,
        "product": product,
    }
    return render(request, "products/products_form.html", context)


def delete_product(request, id):
    """A view that set the is_deleted attribute to True"""
    if request.method == "POST":
        product = Product.objects.get(id=id)
        # Checking to see if the get returns the product incase product has allready been deleted from database.
        if product:
            product.is_deleted = True
            product.save()
            
    return redirect(reverse("products"))
        

products/templates/products/add-to-bag-form.html
<!-- From boutique_ado Project -->

<form class="form" method="POST" action="{% url 'add_to_bag' product.id %}">
    {% csrf_token %}
    <div class="form-group float-right" style="width:60%; padding-left:.8rem; height: 80%;">
        <div class="input-group">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm btn-black rounded-0" data-item_id="{{ product.id }}"
                    id="decrement-qty_{{ product.id }}">
                    {% comment %} <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span> {% endcomment %}
                </button>
            </div>
            
            <input class="form-control form-control-sm qty_input" type="number" name="quantity"
                value="0" min="1" max="99" data-item_id="{{ product.id }}"
                id="id_qty_{{ product.id }}">
            <div class="input-group-append">
                <button class="increment-qty btn btn-sm btn-black rounded-0" data-item_id="{{ product.id }}"
                    id="increment-qty_{{ product.id }}">
                    {% comment %} <span>
                        <i class="fas fa-plus fa-sm"></i>
                    </span> {% endcomment %}
                </button>
            </div>
        </div>
    </div>
    <input type="hidden" name="redirect_url" value="{{ request.path }}">
    <br>

    <button type="submit" class="center btn btn-success" style="padding:.3rem;">Add to cart</button>

</form>

products/templates/products/add-to-cart-form.html
<!-- From boutique_ado Project -->

<form class="form" method="POST" action="{% url 'add_to_bag' product.id %}">
    {% csrf_token %}
    <div class="form-group float-right" style="width:60%; padding-left:.8rem; height: 80%;">
        <div class="input-group">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm btn-black rounded-0" data-item_id="{{ product.id }}"
                    id="decrement-qty_{{ product.id }}">
                    <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span>
                </button>
            </div>
            <input class="form-control form-control-sm qty_input" type="number" name="quantity"
                value="{{ product.quantity }}" min="1" max="99" data-item_id="{{ product.id }}"
                id="id_qty_{{ product.id }}">
            <div class="input-group-append">
                <button class="increment-qty btn btn-sm btn-black rounded-0" data-item_id="{{ product.id }}"
                    id="increment-qty_{{ product.id }}">
                    <span>
                        <i class="fas fa-plus fa-sm"></i>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <input type="hidden" name="redirect_url" value="{{ request.path }}">
    <br>

    <button type="submit" class="center btn btn-success" style="padding:.3rem;">Add to cart</button>

</form>

products/templates/products/add_to_bag_form.html
<form class="form add_to_bag_form_{{ product.id }} float-right mr-3"  style="margin-right:1rem;width:30%;" method="POST" action="{% url 'add_to_bag' product.id %}">
    {% csrf_token %}
    <div class="form-group ml-auto">
        <div class="input-group">
            <input class="form-control form-control-sm qty_input" type="number" name="quantity"
                value="1" min="1" max="99" data-item_id="{{ product.id }}"
                id="id_qty_{{ product.id }}">
        </div>
    </div>
    <input type="hidden" name="redirect_url" value="{{ request.path }}">
</form>

products/templates/products/all_products.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container">
    <div id="container" class="mb-4" style="">
        <div class="loading">
            <i class="icon-spinner icon-spin icon-large"></i>
            Loading data from our servers
        </div>
    </div>
    {{ country_data | json_script:"country_data" }}
    <div class="row">
        <a class="view_bag_button btn btn-success" href="{% url 'view_bag' %}">View Bag</a>
    </div>
    <div class="row">
        {% for product in products %}
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-2 mb-2">
            <div class="card border-0">
                {% if product.image and product.image_2 %}
                <img class="all-products-image card-img-top img-fluid" src="{{MEDIA_URL}}{{ product.image }}" alt="{{ product.name }}"
                    onmouseover="this.src='{{MEDIA_URL}}{{ product.image_2 }}';"
                    onmouseout="this.src='{{MEDIA_URL}}{{ product.image }}';">
                
                {% else %}
                    <img class="all-products-image card-img-top img-fluid" src="{{MEDIA_URL}}{{ product.image }}" onmouseover="this.src='{{ MEDIA_URL }}noimage.png';"
                    onmouseout="this.src='{{ MEDIA_URL }}{{ product.image }}';" alt="{{ product.name }}">
                {% endif %}
                <div class="card-body text-center">
                    <h5>{{ product.product_name }}</h5>
                    {% if product.color == "" %}
                        <h6 class="card-title"><br></h6>
                    {% else %}
                        <h6 class="card-title">{{ product.color }}</h6>
                    {% endif %}
                    <div class=" product_price_quantity pb-2">
                        <div class="row">
                            <div class="col-md-12">
                                <span class="float-left ml-2">Price:</span>
                                <span  class="float-right mr-3">${{ product.price }}</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <span  class="float-left ml-2 mt-1">Quantity: </span>
                                {% include "products/add_to_bag_form.html" %}
                            </div>
                        </div>
                        <div class="row">
                            {% if request.user.is_superuser %}
                            <div class="col-md-6 col-sm-12">
                                <a class="btn btn-info btn-sm px-3 mt-1" href="{% url 'update_product' product.id %}">Update</a>
                            </div>
                            {% if product.number_in_stock == 0 %}
                                <div class="col-md-6 col-sm-12">
                                    <a class="center btn btn-danger btn-sm add_to_bag  p-1 mt-1" disabled="disabled">Not in stock</a>
                                </div>
                                {% else %}
                                <div class="col-md-6 col-sm-12">
                                    <a class="btn btn-success btn-sm add_to_bag p-1 mt-1" id="{{ product.id }}" >Add to bag</a>
                                </div>
                            {% endif %}
                            
                            {% else %}
                                {% if product.number_in_stock == 0 %}
                                    <div class="col-md-12">
                                        <a class="center btn btn-danger btn-sm add_to_bag" disabled="disabled">Not in stock</a>
                                    </div>
                                    {% else %}
                                    <div class="col-md-12">
                                        <a class="center btn btn-success btn-sm add_to_bag" id="{{ product.id }}">Add to bag</a>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                        
                    </div>
                    
                </div>
            </div>
        </div>
        {% endfor %}
        

    </div>
</div>

<script>

    $(".add_to_bag").click(function(e){
        let form = $(`.add_to_bag_form_${this.id}`)
        console.log(form)
        form.submit()
    });
</script>
{% endblock %}
{% block extra_js %}
{{ block.super }}

<script src="{% static 'map/js/map.js' %}"></script>

{% endblock %}

products/templates/products/products_form.html
{% extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container h-100 mt-3">
		<div class="justify-content-center h-100">
			<div class="product_card">
				<div class="justify-content-center">
					{% if product %}
                        <h3 class="text-center">Update Product</h3>
                    {% else %}
                        <h3 class="text-center">Add Product</h3>
                    {% endif %}
				</div>
				<div class="justify-content-center form_container">
					<form class="form-group mx-auto" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    {{ form.supplier.label }}
                                    <br>
                                    {{ form.supplier }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    {{ form.product_name.label }}
                                    <br>
                                    {{ form.product_name }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    {{ form.price.label }}
                                    <br>
                                    {{ form.price }}
                                </div>
                                
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    {{ form.color.label }}
                                    <br>
                                    {{ form.color }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    {{ form.number_in_stock.label }}
                                    <br>
                                    {{ form.number_in_stock }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    {{ form.image.label }}
                                    <br>
                                    {{ form.image }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    {{ form.image_2.label }}
                                    <br>
                                    {{ form.image_2 }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 mb-3">
                                    <h8>Current image</h8>
                                    <br>
                                    <img class="img-fluid" style="height:6.25rem;" src="{{ form.instance.image.url }}" />
                                </div>
                                <div class="col-md-2  mb-3">
                                    <h8>Selected image</h8>
                                    <br>
                                    <img class="img-fluid" style="height:6.25rem;" id="id_image_image"/>
                                </div>
                                <div class="col-md-3 mb-3 offset-md-1">
                                    <h8>Current image</h8>
                                    <br>
                                    <img class="img-fluid" style="height:6.25rem;" src="{{ form.instance.image_2.url }}" />
                                </div>
                                <div class="col-md-2 mb-3">
                                    <h8>Selected image</h8>
                                    <br>
                                    <img class="img-fluid" style="height:6.25rem;" id="id_image_2_image"/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 mb-3">
                                    <div class="form_errors">{{ form_errors }}</div>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center mt-3 product_container">
                                {% if product %}
                                    <button class="btn btn-info" type="submit">Update</button>
                                    <a class="btn btn-danger ml-2" data-toggle="modal" data-target="#deleteProduct">Delete</a>
                                {% else %}
                                    <button class="btn btn-success" type="submit">Add Product</button>
                                {% endif %}
                            </div>
					</form>

				</div>
		</div>
	</div>
    {% if product %}
    <div class="modal fade" id="deleteProduct" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteProductLabel">Delete Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="deleteForm" method="POST" action="{% url 'delete_product' product.id %}">
                        {% csrf_token %}
                        <h6>Are you sure you want to remove this product</h6>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="delete-form btn btn-danger ml-auto" type="submit">Confirm</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}
{% block postloadjs %}
    <script>
        let form = $("#deleteForm")
        $(".delete-form").click(function(){
            form.submit()
        })

        $("#id_image").change(function(input){
            readURL(this)
        })
        $("#id_image_2").change(function(input){
            readURL(this)
        })

        function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            output = "#" + input.id + "_image"
            reader.onload = function(e) {
                $(output).attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
{% endblock %}